#!/usr/bin/env python3
"""Build the autonomous StarLine production frontend module."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "custom_components" / "starline_telemetry" / "frontend"
SOURCES = (
    "starline-app-v003.js",
    "starline-app-v004.js",
    "starline-app-v005.js",
    "starline-app-v007.js",
    "starline-app-v008.js",
    "starline-app-v009.js",
    "starline-app-v010.js",
    "starline-app-v011.js",
    "starline-app-v012.js",
    "starline-app-v013.js",
    "starline-app-v014.js",
    "starline-app-v015.js",
    "starline-app-v016.js",
    "starline-app-v017.js",
)
TARGET = FRONTEND / "starline-app.js"


def source_body(name: str) -> str:
    lines = (FRONTEND / name).read_text(encoding="utf-8").splitlines()
    if lines and lines[0].startswith("import "):
        lines = lines[1:]
    return "\n".join(lines).strip()


def main() -> None:
    blocks = [
        "// Generated by scripts/build_frontend_bundle.py.",
        "// Autonomous production module: no runtime imports.",
    ]
    for name in SOURCES:
        blocks.append(f"\n// BEGIN {name}\n{{\n{source_body(name)}\n}}\n// END {name}")
    TARGET.write_text("\n".join(blocks) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
