#!/usr/bin/env python3
"""Build the autonomous StarLine production frontend module."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "custom_components" / "starline_telemetry" / "frontend"
SOURCE = FRONTEND / "starline-panel-source.js"
TARGET = FRONTEND / "starline-app.js"


def build() -> str:
    header = [
        "// Generated by scripts/build_frontend_bundle.py.",
        "// Autonomous production module generated from starline-panel-source.js.",
    ]
    source = SOURCE.read_text(encoding="utf-8").strip()
    return "\n".join(header) + "\n\n" + source + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = build()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            raise SystemExit("Frontend production bundle is missing or stale")
        return
    TARGET.write_text(content, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
