#!/usr/bin/env python3
"""Build the autonomous StarLine production frontend module."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "custom_components" / "starline_telemetry" / "frontend"
SOURCE = FRONTEND / "starline-panel-source.js"
TARGET = FRONTEND / "starline-app.js"


def main() -> None:
    header = [
        "// Generated by scripts/build_frontend_bundle.py.",
        "// Autonomous production module generated from starline-panel-source.js.",
    ]
    source = SOURCE.read_text(encoding="utf-8").strip()
    TARGET.write_text("\n".join(header) + "\n\n" + source + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
